name: Hex Artifactory Example

on: [workflow_dispatch, push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install OTP and Elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: 26.2.1
          elixir-version: 1.16.1
          version-type: strict
  
      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_URL: ${{ secrets.JF_URL }}
          JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}

      # This command adds a new server configuration to the JFrog CLI  
      - name: Setup JFrog CLI - Server
        run: |
          export SERVER_ID="test"
          jf c add $SERVER_ID --url=$URL --access-token=$ACCESS_TOKEN --interactive=false
          
      - name: Setup Test JFrog CLI 
        run: jf --version

      - name: Setup Test JFrog Ping 
        run: jf rt ping

      - name: Check local build directory - pre-build 
        run: ls -la ./todos

      - name: Make Deps directory for downlaod from Artifactory 
        run: |
          mkdir ./todos/deps
          mkdir ./todos/tarballs

      - name: Download Deps from Artifactory and unpack tars 
        run: jf rt dl hex-depend-local/todos/tarballs/ ./todos/tarballs/ --include-dirs

      - name: Check Deps download from Artifactory  
        run: ls -la ./todos/tarballs/ 

      - name: Untar all deps for usage
        run: |
          if find ./todos/tarballs/ -mindepth 1 -maxdepth 1 | read; then
            echo "Deps Downloaded Found"
            ## tar xvf ./todos/deps/*.tar.gz
          else
            echo "No Deps Found"
          fi

      - name: Check Deps untarred from in directory   
        run: ls -la ./todos/deps 

      - name: Set Unsafe to True 
        run:  mix hex.config unsafe_https true
        
      - name: Install dependencies
        working-directory: ./todos
        run: mix deps.get

      - name: Check local build directory - post-build 
        run: ls -la ./todos/deps/

      - name: Build App
        run: |
          cd  ./todos 
          mix hex.build
          ls -la
        
      - name: Start to Process Build to Artifactory 
        run: jf rt build-add-git hex-build 2.0.${{github.run_number}}

      - name: Collect Env Vars 
        run: jf rt build-collect-env hex-build 2.0.${{github.run_number}}

      - name: Package up deps 
        run: |
          rm -rf tarballs/
          cd ./todos/deps && for dir in *; do tar czf "../tarballs/${dir}.tar.gz" "$dir";  done
          ls -la ../tarballs

      - name: Upload deps to Artifactory 
        run: jf rt u "./todos/tarballs/*.tar.gz" hex-depend-local/

      - name: Add deps to build depenencies 
        run: jf rt build-add-dependencies hex-build 2.0.${{github.run_number}} "./todos/tarballs/*.tar.gz" 

      - name: Uplaod build to Artifactory 
        run: |
          ls -la ./todos
          jf rt u "./todos/*.tar" test-hex-dev/test-app/todos-0.1.0.tar --build-name hex-build --build-number 2.0.${{github.run_number}} 
          
      - name: Publish build to Artifactory 
        run: jf rt build-publish hex-build 2.0.${{github.run_number}}
        

      
