name: "Hex Artifactory Example"
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install OTP and Elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: 26.2.1
          elixir-version: 1.16.1
          version-type: strict
      - name: Setup JFrog CLI
      - uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_URL: ${{ secrets.JF_URL }}
          JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}
      - run: jf --version
      - run: jf rt ping
      - name: Run JFrog CLI
        run: |
          # Collect environment variables for the build
          jfrog rt bce
          # Collect VCS details from git and add them to the build
          jfrog rt bag
          # Publish build info
          jfrog rt bp
