name: Hex Artifactory Example

on: [workflow_dispatch, push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install OTP and Elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: 26.2.1
          elixir-version: 1.16.1
          version-type: strict
          
      - name: Set Unsafe to True 
        run:  mix hex.config unsafe_https true
        
      - name: Install dependencies
        working-directory: ./todos
        run: mix deps.get

      - name: Check mix format
        working-directory: ./todos
        run: mix format --check-formatted
  
      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_URL: ${{ secrets.JF_URL }}
          JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}

      # This command adds a new server configuration to the JFrog CLI  
      - name: Setup JFrog CLI - Server
        run: |
          export SERVER_ID="test"
          jf c add $SERVER_ID --url=$URL --access-token=$ACCESS_TOKEN --interactive=false
          
      - name: Setup Test JFrog CLI 
        run: jf --version

      - name: Setup Test JFrog Ping 
        run: jf rt ping
        
      - name: Start to Process Build to Artifactory 
        run: |
          jf rt build-add-git hex-build 2.0.${{github.run_number}}
          jf rt build-collect-env hex-build 2.0.${{github.run_number}}
          find ./todos/deps/ -maxdepth 1 -type d -exec tar czf $(basename {}).tar {} \;
          jf rt u "./todos/deps/*.tar" hex-depend-local/
          jf rt build-add-dependencies hex-build 2.0.${{github.run_number}} "./todos/deps/*.tar" 
          jf rt u "./todos/*.tar"  hex-virt/test-app/todos-0.1.0.tar  --build-name hex-build --build-number 2.0.${{github.run_number}}
          jf rt build-publish hex-build 2.0.${{github.run_number}}
        

      
